# Generated by Django 4.2.9 on 2025-01-03 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('adoption', 'Adoption Events'), ('training', 'Training Workshops'), ('show', 'Pet Shows'), ('vet', 'Vet Camps'), ('social', 'Social Meetups')], default='social', max_length=20),
        ),
    ]
