# Generated by Django 4.2.9 on 2025-01-03 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_event_options_alter_event_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundraiser',
            name='donation_history',
            field=models.TextField(blank=True, default='[]'),
        ),
    ]
