# Generated by Django 4.2.9 on 2025-01-03 19:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_business_address_business_business_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
