# Generated by Django 4.2.9 on 2025-01-03 19:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_create_professional_records'),
    ]

    operations = [
        migrations.AddField(
            model_name='petsittergroomer',
            name='availability',
            field=models.TextField(blank=True, default='Monday-Friday: 9 AM - 5 PM'),
        ),
        migrations.AddField(
            model_name='petsittergroomer',
            name='house_calls',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='petsittergroomer',
            name='service_area',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='petsittergroomer',
            name='service_types',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='petsittergroomer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='shelterclinic',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shelterclinic',
            name='emergency_service',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shelterclinic',
            name='facilities',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='shelterclinic',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='shelterclinic',
            name='working_hours',
            field=models.TextField(blank=True, default='Monday-Friday: 9 AM - 5 PM'),
        ),
        migrations.AddField(
            model_name='shop',
            name='business_hours',
            field=models.TextField(blank=True, default='Monday-Friday: 9 AM - 5 PM', null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='contact_info',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='petsittergroomer',
            name='experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='petsittergroomer',
            name='rating',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='shop',
            name='rating',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
