# Generated by Django 4.2.9 on 2025-01-03 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_petsittergroomer_availability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='product_name',
            field=models.CharField(default='Shop Products', max_length=100),
        ),
        migrations.AlterField(
            model_name='shop',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shop',
            name='status',
            field=models.CharField(default='active', max_length=20),
        ),
    ]
